[package]
name = "rice_coder"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
binggan = "0.10.0"
proptest = "1.5.0"
rand = "0.8.5"
zipf = "7.0.1"

[[bench]]
name = "bench"
harness = false


[profile.release]
opt-level = 3      # Full optimization for performance
debug = true
